
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async setSettingsUi(settings: SettingsUi) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings_ui", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettingsUi() : Promise<SettingsUi | null> {
    return await TAURI_INVOKE("get_settings_ui");
},
async setSettingsGit(settings: SettingsGit) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings_git", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettingsGit() : Promise<SettingsGit | null> {
    return await TAURI_INVOKE("get_settings_git");
},
async setSettingsGithub(settings: SettingsGitHub) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings_github", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettingsGithub() : Promise<SettingsGitHub | null> {
    return await TAURI_INVOKE("get_settings_github");
},
async setSettingsJira(settings: SettingsJira) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings_jira", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettingsJira() : Promise<SettingsJira | null> {
    return await TAURI_INVOKE("get_settings_jira");
},
async setSettingsZulip(settings: SettingsZulip) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings_zulip", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettingsZulip() : Promise<SettingsZulip | null> {
    return await TAURI_INVOKE("get_settings_zulip");
},
async setSettingsIcal(settings: SettingsIcal) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_settings_ical", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettingsIcal() : Promise<SettingsIcal | null> {
    return await TAURI_INVOKE("get_settings_ical");
},
/**
 * Kicks off a background iCal sync. Returns immediately; poll `get_ical_sync_status` for progress.
 */
async triggerIcalSync() : Promise<void> {
    await TAURI_INVOKE("trigger_ical_sync");
},
async getIcalSyncStatus() : Promise<IcalSyncStatus> {
    return await TAURI_INVOKE("get_ical_sync_status");
},
async getTimelineForDay(day: string) : Promise<Result<TimelineEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_timeline_for_day", { day }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTimelineHarvestDoneForEventIds(eventIds: string[]) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_timeline_harvest_done_for_event_ids", { eventIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTimelineHarvestDone(eventId: string, done: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_timeline_harvest_done", { eventId, done }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearAllCaches() : Promise<Result<ClearCachesResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_all_caches") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCacheSize() : Promise<Result<CacheSizeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_size") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCachedDayEventCounts() : Promise<Result<{ [key in string]: number }, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cached_day_event_counts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type CacheSizeResult = { bytes: number; cached_days: number }
export type ClearCachesResult = { rows_deleted: number }
export type GitHubEvent = "PullRequestEvent" | "PullRequestReviewEvent" | "PullRequestReviewCommentEvent" | "IssuesEvent" | "IssueCommentEvent"
export type IcalSyncStatus = { syncing: boolean; last_synced_at: number | null; last_error: string | null }
/**
 * Timeline categories for Jira activity (mapped to REST/changelog rules in the Jira timeline source).
 */
export type JiraEvent = 
/**
 * Comments you authored on issues.
 */
"CommentWritten" | 
/**
 * Issues where you are the reporter/creator.
 */
"IssueCreated" | 
/**
 * Issues transitioned into a Done-style status category.
 */
"IssueCompleted" | 
/**
 * You were @mentioned in an issue field or comment body.
 */
"Mentioned"
export type SettingsGit = { enabled: boolean; path: string }
export type SettingsGitHub = { enabled: boolean; username: string; token: string; enabled_events: GitHubEvent[] }
export type SettingsIcal = { enabled?: boolean; urls?: string[]; 
/**
 * User's email address used to identify their ATTENDEE entry and filter declined events.
 */
email?: string | null }
export type SettingsJira = { enabled: boolean; site_url?: string; email?: string; api_token?: string; enabled_events?: JiraEvent[] }
export type SettingsUi = { theme: string }
export type SettingsZulip = { enabled: boolean; realm_url?: string; email?: string; api_key?: string }
/**
 * One row on the timeline (all sources normalize to this shape).
 */
export type TimelineEvent = { 
/**
 * Stable id for UI state (e.g. Harvest toggles). Must be unique per logical activity and
 * identical across fetches/days — used for DB-backed toggles. Prefer a namespaced string
 * (`git:…`, `gmail:…`, `zulip:…`) so ids never collide across sources.
 */
id: string; 
/**
 * Local time `HH:MM` for the selected calendar day.
 */
time: string; source: TimelineEventSource; title: string; detail: string | null; url: string | null }
/**
 * Activity source for the day timeline (matches frontend `TimelineEvent` styling keys).
 */
export type TimelineEventSource = "git" | "github" | "calendar" | "gmail" | "drive" | "jira" | "zulip"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
